### ISSUE TITLE
[Feature request] Allow balancing policy based on user_gid

### ISSUE THREAD

**Issue by jonathonf** [pkolano/ballast#4]
Looking at the documentation it's possible to set balancing policy based on a user's UID (`user_uid`). It would be great to extend this to allow balancing based on the user's GID.

This would allow much easier management of hosts which are (primarily and/or solely) used by specific user groups.

**Comment by pkolano** [comment]
hi Jonathon,

Sorry, just saw this today (must have notifications turned off).  Should be an easy addition so will put this in shortly.

**Comment by pkolano** [comment]
There is now a user_gid field in v2.2

**Comment by notpeter** [comment]
Relevant commit for v2.2: https://github.com/pkolano/ballast/commit/9193e899cb0ec450e9a896ad29e28c4421a7eebe

**Comment by jonathonf** [comment]
Awesome, thank you!
